name: Testes automatizados

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Instalar navegador
        run: python -m playwright install --with-deps chromium

      - name: Executar testes
        run: |
          for arquivo in automacao/test_*.py; do
            xvfb-run -a python "$arquivo"
          done